# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            welcloud.io
description:      'Ce blog est consacré au cloud computing, à l''ingénierie logicielle et aux pratiques agiles.'
baseurl:          /
baseurl_fortwitter: http://welcloud.io

author:
  name:           'Olivier Lemaitre'
  twitter:        o_lemaitre
